services:
  mysql:
    image: mysql:8.0
    container_name: meters_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: infoenergo
      MYSQL_USER: infoenergo
      MYSQL_PASSWORD: infopass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: meters_django
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - ./app/cEnergo.env
    volumes:
      - ./django_app:/app
      - ./logs:/app/logs
      - ./Catalog.xlsx:/app/Catalog.xlsx
      - ./app/cEnergo.env:/app/cEnergo.env
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=infoenergo
      - MYSQL_USER=infoenergo
      - MYSQL_PASSWORD=infopass
    command: sh -c "python wait_for_mysql.py && python manage.py runserver 0.0.0.0:8000"
  # Службы синхронизации
  sync-mssql:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: meters_sync_mssql
    restart: always
    depends_on:
      - mysql
      - django
    env_file:
      - ./app/cEnergo.env
    volumes:
      - ./django_app:/app
      - ./logs:/app/logs
      - ./app/cEnergo.env:/app/cEnergo.env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=infoenergo
      - MYSQL_USER=infoenergo
      - MYSQL_PASSWORD=infopass
    command: python manage.py sync_mssql

  sync-sanxing-old:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: meters_sync_sanxing_old
    restart: always
    depends_on:
      - mysql
      - django
    env_file:
      - ./app/cEnergo.env
    volumes:
      - ./django_app:/app
      - ./logs:/app/logs
      - ./app/cEnergo.env:/app/cEnergo.env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=infoenergo
      - MYSQL_USER=infoenergo
      - MYSQL_PASSWORD=infopass
    command: python manage.py sync_sanxing

  sync-sanrise:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: meters_sync_sanrise
    restart: always
    depends_on:
      - mysql
      - django
    env_file:
      - ./app/cEnergo.env
    volumes:
      - ./django_app:/app
      - ./logs:/app/logs
      - ./app/cEnergo.env:/app/cEnergo.env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=infoenergo
      - MYSQL_USER=infoenergo
      - MYSQL_PASSWORD=infopass
    command: python manage.py sync_sanrise

  sync-hexing-kuk:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: meters_sync_hexing_kuk
    restart: always
    depends_on:
      - mysql
      - django
    env_file:
      - ./app/cEnergo.env
    volumes:
      - ./django_app:/app
      - ./logs:/app/logs
      - ./app/cEnergo.env:/app/cEnergo.env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=infoenergo
      - MYSQL_USER=infoenergo
      - MYSQL_PASSWORD=infopass
    command: python manage.py sync_hexing

  sync-risesun:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: meters_sync_risesun
    restart: always
    depends_on:
      - mysql
      - django
    env_file:
      - ./app/cEnergo.env
    volumes:
      - ./django_app:/app
      - ./logs:/app/logs
      - ./app/cEnergo.env:/app/cEnergo.env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=infoenergo
      - MYSQL_USER=infoenergo
      - MYSQL_PASSWORD=infopass
    command: python manage.py sync_risesun

  sync-sanxing-new-100a:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: meters_sync_sanxing_new_100a
    restart: always
    depends_on:
      - mysql
      - django
    env_file:
      - ./app/cEnergo.env
    volumes:
      - ./django_app:/app
      - ./downloads:/app/downloads
      - ./app/cEnergo.env:/app/cEnergo.env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=infoenergo
      - MYSQL_USER=infoenergo
      - MYSQL_PASSWORD=infopass
    command: python manage.py sync_website --daemon --verbose

  sync-sanxing-new-5a:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: meters_sync_sanxing_new_5a
    restart: always
    depends_on:
      - mysql
      - django
    env_file:
      - ./app/cEnergo.env
    volumes:
      - ./django_app:/app
      - ./downloads:/app/downloads
      - ./app/cEnergo.env:/app/cEnergo.env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=infoenergo
      - MYSQL_USER=infoenergo
      - MYSQL_PASSWORD=infopass
    command: python manage.py sync_website_period1 --daemon --verbose

  sync-star:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: meters_sync_star
    restart: always
    depends_on:
      - mysql
      - django
    env_file:
      - ./app/cEnergo.env
    volumes:
      - ./django_app:/app
      - ./downloads:/app/downloads
      - ./app/cEnergo.env:/app/cEnergo.env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=infoenergo
      - MYSQL_USER=infoenergo
      - MYSQL_PASSWORD=infopass
    command: python manage.py sync_star --daemon --verbose

  sync-hxn-pop:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: meters_sync_hexing_pop
    restart: always
    depends_on:
      - mysql
      - django
    env_file:
      - ./app/cEnergo.env
    volumes:
      - ./django_app:/app
      - ./downloads:/app/downloads
      - ./app/cEnergo.env:/app/cEnergo.env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=infoenergo
      - MYSQL_USER=infoenergo
      - MYSQL_PASSWORD=infopass
    command: python manage.py sync_hxn --daemon --verbose
volumes:
  mysql_data:
