# Generated by Django 5.2.15 on 2026-06-22 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_code', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('digit_capacity', models.CharField(max_length=10)),
                ('phases', models.IntegerField()),
                ('nominal_current', models.CharField(max_length=20)),
                ('nominal_voltage', models.CharField(max_length=20)),
                ('system_type', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=20)),
                ('device_type_id', models.CharField(max_length=20)),
                ('device_type_str', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'meter_models',
            },
        ),
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_name', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('last_update', models.DateTimeField()),
                ('records_processed', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_status',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('nominal_current', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('phase', models.IntegerField(blank=True, null=True)),
                ('askue_id', models.CharField(blank=True, max_length=20)),
                ('api_id', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meters.metermodel')),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('reading_value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meters.device')),
            ],
            options={
                'db_table': 'readings',
                'indexes': [models.Index(fields=['device', 'timestamp'], name='readings_device__cccd55_idx'), models.Index(fields=['timestamp'], name='readings_timesta_1e7c66_idx'), models.Index(fields=['notes', 'timestamp'], name='readings_notes_dec5d3_idx')],
                'unique_together': {('device', 'timestamp')},
            },
        ),
    ]
