# Generated by Django 5.2.15 on 2026-06-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='api_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='askue_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='nominal_current',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='metermodel',
            name='catalog_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='metermodel',
            name='device_type_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='metermodel',
            name='device_type_str',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='metermodel',
            name='digit_capacity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='metermodel',
            name='nominal_current',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='metermodel',
            name='nominal_voltage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='metermodel',
            name='period',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='metermodel',
            name='system_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reading',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
