# Generated by Django 5.2.15 on 2026-06-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0003_alter_device_api_id_alter_device_askue_id_and_more'),
    ]

    operations = [
    ]
