# Generated by Django 5.2.15 on 2026-06-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0004_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metermodel',
            name='catalog_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='metermodel',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
    ]
