# Generated by Django 5.2.15 on 2026-07-08 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0005_alter_metermodel_catalog_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'feeders',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'substations',
            },
        ),
        migrations.CreateModel(
            name='TransformerSubstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'transformer_substations',
            },
        ),
        migrations.RenameIndex(
            model_name='reading',
            new_name='idx_readings_dev_ts',
            old_name='readings_device__cccd55_idx',
        ),
        migrations.RenameIndex(
            model_name='reading',
            new_name='idx_readings_ts',
            old_name='readings_timesta_1e7c66_idx',
        ),
        migrations.RenameIndex(
            model_name='reading',
            new_name='idx_readings_notes_ts',
            old_name='readings_notes_dec5d3_idx',
        ),
        migrations.AddField(
            model_name='metermodel',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feeder',
            name='head_meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeder_head', to='meters.device', verbose_name='Головной счётчик фидера'),
        ),
        migrations.AddField(
            model_name='device',
            name='feeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='meters.feeder'),
        ),
        migrations.AddField(
            model_name='region',
            name='head_meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_head', to='meters.device', verbose_name='Головной счётчик района'),
        ),
        migrations.AddField(
            model_name='device',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='meters.region'),
        ),
        migrations.AddField(
            model_name='substation',
            name='head_meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substation_head', to='meters.device', verbose_name='Головной счётчик подстанции'),
        ),
        migrations.AddField(
            model_name='substation',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substations', to='meters.region'),
        ),
        migrations.AddField(
            model_name='feeder',
            name='substation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeders', to='meters.substation'),
        ),
        migrations.AddField(
            model_name='device',
            name='substation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='meters.substation'),
        ),
        migrations.AddField(
            model_name='transformersubstation',
            name='feeder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tps', to='meters.feeder'),
        ),
        migrations.AddField(
            model_name='transformersubstation',
            name='head_meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tp_head', to='meters.device', verbose_name='Головной счётчик ТП'),
        ),
        migrations.AddField(
            model_name='device',
            name='tp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='meters.transformersubstation'),
        ),
        migrations.AlterUniqueTogether(
            name='substation',
            unique_together={('region', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='feeder',
            unique_together={('substation', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='transformersubstation',
            unique_together={('feeder', 'name')},
        ),
    ]
