# Generated by Django 5.2.16 on 2026-07-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0006_feeder_region_substation_transformersubstation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'device_groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='devices', to='meters.devicegroup'),
        ),
    ]
