# Generated by Django 5.2.16 on 2026-07-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0007_devicegroup_device_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='registration_source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Источник регистрации'),
        ),
    ]
