# Generated by Django 5.2.17 on 2026-08-13 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0008_device_registration_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_1c', models.CharField(db_index=True, max_length=50)),
                ('model_1c', models.CharField(blank=True, max_length=100)),
                ('model_db', models.CharField(blank=True, max_length=100)),
                ('model_match_type', models.CharField(choices=[('exact', 'Полное'), ('partial', 'Частичное'), ('none', 'Не совпадает')], default='none', max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('last_reading_date', models.DateTimeField(blank=True, null=True)),
                ('last_reading_value', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('action_type', models.CharField(choices=[('ok', 'OK'), ('fix_model', 'Исправить модель'), ('fix_serial', 'Исправить номер'), ('offline', 'Проверить связь'), ('not_found', 'Не найден')], default='not_found', max_length=20)),
                ('action_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новое'), ('fixed', 'Исправлено'), ('ignored', 'Пропущено'), ('in_progress', 'В работе')], default='new', max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Комментарий оператора')),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_date', models.DateField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meters.device')),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meters.region')),
            ],
            options={
                'db_table': 'compare_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['serial_1c'], name='compare_res_serial__4fc6c0_idx'), models.Index(fields=['status'], name='compare_res_status_a175bc_idx'), models.Index(fields=['action_type'], name='compare_res_action__e2e7c7_idx'), models.Index(fields=['check_date'], name='compare_res_check_d_4dadcc_idx')],
            },
        ),
    ]
