# Generated by Django 5.2.17 on 2026-08-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0009_compareresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareresult',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
