# Generated by Django 5.2.17 on 2026-08-13 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0010_alter_compareresult_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareresult',
            name='upload_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compare_results', to='meters.region', verbose_name='Район загрузки'),
        ),
    ]
