# Generated by Django 5.2.17 on 2026-08-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0011_compareresult_upload_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareresult',
            name='action_type',
            field=models.CharField(choices=[('ok', 'OK'), ('fix_model', 'Исправить Тип ПУ'), ('fix_serial', 'Исправить номер'), ('offline', 'Проверить связь'), ('not_found', 'Не найден')], default='not_found', max_length=20),
        ),
        migrations.AlterField(
            model_name='compareresult',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('fixed', 'Исправлено'), ('ignored', 'Пропущено'), ('in_progress', 'В работе'), ('auto_fixed', 'Автозакрыто')], default='new', max_length=20),
        ),
    ]
