# Generated by Django 5.2.17 on 2026-08-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0012_alter_compareresult_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('repair', 'Ремонт'), ('inactive', 'Отключен'), ('temporary_off', 'Временно отключен')], default='active', max_length=20),
        ),
    ]
