# Generated by Django 5.2.17 on 2026-08-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0013_alter_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareresult',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
