# Generated by Django 5.2.17 on 2026-08-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0014_compareresult_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compareresult',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='compareresult',
            name='verified',
            field=models.BooleanField(default=False, help_text='Отметка о проверке исправления администратором/оператором'),
        ),
    ]
