# Generated by Django 5.2.17 on 2026-08-24 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0016_alter_compareresult_action_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingFetchTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('error', 'Ошибка')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_loaded', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meters.device')),
            ],
            options={
                'db_table': 'reading_fetch_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
