# Generated by Django 5.2.17 on 2026-08-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0017_readingfetchtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.CharField(blank=True, choices=[('population', 'Население'), ('commercial', 'Коммерческие'), ('industrial', 'Промышленные'), ('budget', 'Бюджет'), ('agriculture', 'Сельхоз'), ('other', 'Прочие')], default=None, max_length=20, null=True),
        ),
    ]
