# Generated by Django 5.2.17 on 2026-08-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0018_device_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(blank=True, choices=[('population', 'Население'), ('commercial', 'Коммерческие'), ('industrial', 'Промышленные'), ('budget', 'Бюджет'), ('agriculture', 'Сельхоз'), ('other', 'Прочие'), ('other2', 'Не указан')], default=None, max_length=20, null=True),
        ),
    ]
