# Generated by Django 5.2.17 on 2026-08-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0019_alter_device_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_head_meter',
            field=models.BooleanField(default=False, help_text='Является головным счётчиком для ТП/фидера/подстанции/района'),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(blank=True, choices=[('population', 'Население'), ('commercial', 'Коммерческие'), ('industrial', 'Промышленные'), ('budget', 'Бюджет'), ('agriculture', 'Сельхоз'), ('other', 'Прочие')], default=None, max_length=20, null=True),
        ),
    ]
