# Generated by Django 5.2.17 on 2026-08-28 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0020_device_is_head_meter_alter_device_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='direction',
            field=models.CharField(choices=[('aplus', 'A+'), ('aminus', 'A-')], default='aplus', max_length=20, verbose_name='Направление учёта'),
        ),
        migrations.AddField(
            model_name='device',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ввода'),
        ),
        migrations.AddField(
            model_name='device',
            name='meter_type',
            field=models.CharField(choices=[('active', 'Активный'), ('reactive', 'Реактивный')], default='active', max_length=20, verbose_name='Тип счётчика'),
        ),
        migrations.AddField(
            model_name='device',
            name='replacement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата замены'),
        ),
        migrations.AddField(
            model_name='device',
            name='tn_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Коэффициент ТН'),
        ),
        migrations.AddField(
            model_name='device',
            name='tt_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Коэффициент ТТ'),
        ),
        migrations.AddField(
            model_name='feeder',
            name='direction',
            field=models.CharField(choices=[('receive', 'Приём'), ('give', 'Отдача')], default='receive', max_length=20, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='feeder',
            name='feeder_type',
            field=models.CharField(choices=[('input', 'Вводной'), ('output', 'Отходящий')], default='output', max_length=20, verbose_name='Тип фидера'),
        ),
        migrations.AddField(
            model_name='feeder',
            name='voltage_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Уровень напряжения'),
        ),
        migrations.AddField(
            model_name='substation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='substation',
            name='voltage_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CalculationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('period_type', models.CharField(choices=[('decade1', 'Декада 1'), ('decade2', 'декада 2'), ('decade3', 'декада 3'), ('month', 'Месяц')], max_length=10, verbose_name='Тип периода')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meters.substation', verbose_name='ПС')),
            ],
            options={
                'db_table': 'calculation_periods',
                'ordering': ['-year', '-month', 'period_type'],
                'unique_together': {('substation', 'year', 'month', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='BalanceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_energy', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Поступление, кВт·ч')),
                ('output_energy', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Отпуск, кВт·ч')),
                ('imbalance_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Небаланс, кВт·ч')),
                ('imbalance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Небаланс, %')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата расчёта')),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meters.substation', verbose_name='ПС')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meters.calculationperiod', verbose_name='Период')),
            ],
            options={
                'db_table': 'balance_results',
                'ordering': ['-period__year', '-period__month'],
            },
        ),
        migrations.CreateModel(
            name='CoefficientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_ratio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ТТ')),
                ('tn_ratio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ТН')),
                ('start_date', models.DateField(verbose_name='Дата начала действия')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания действия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meters.device', verbose_name='Счётчик')),
            ],
            options={
                'db_table': 'coefficient_history',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MeterConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_object_type', models.CharField(choices=[('substation', 'Подстанция'), ('feeder', 'Фидер'), ('tp', 'ТП')], max_length=20, verbose_name='Тип объекта')),
                ('connected_object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('role', models.CharField(blank=True, max_length=50, null=True, verbose_name='Роль (main/backup)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meters.device', verbose_name='Счётчик')),
            ],
            options={
                'db_table': 'meter_connections',
                'indexes': [models.Index(fields=['connected_object_type', 'connected_object_id'], name='meter_conne_connect_a3b11c_idx')],
            },
        ),
    ]
