# Generated by Django 5.2.17 on 2026-08-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0021_device_direction_device_installation_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reading',
            name='idx_readings_dev_ts',
        ),
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reading',
            name='direction',
            field=models.CharField(choices=[('aplus', 'A+'), ('aminus', 'A-')], default='aplus', max_length=10, verbose_name='Направление учёта'),
        ),
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('device', 'timestamp', 'direction')},
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['device', 'timestamp', 'direction'], name='idx_readings_dev_ts_dir'),
        ),
    ]
