# Generated by Django 5.2.17 on 2026-09-02 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0022_remove_reading_idx_readings_dev_ts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='parent_feeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='meters.feeder', verbose_name='Родительский фидер (для отходящих)'),
        ),
    ]
